  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>Dashboard</h1>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Meus Tickets</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                  title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <table class="table table-bordered table-striped table-hover table-condensed">
          <tr>
            <th style="width: 10px">#</th>
            <th>Titulo</th>
            <th>Prioridade</th>
            <th>Data</th>
            <th>Ação</th>
          </tr>
          <tr>
            <td>1</td>
            <td>Update software</td>
            <td><span class="badge bg-red">Alta</span></td>
            <td><span class="badge bg-light-blue">Em andamento</span></td>
            <td>12/12/2017</td>
            <td>
              <div class="btn-group">
                <a href="edit.html" class="btn btn-warning"><i class="fa fa-edit"></i> Editar</a>
                <a href="delete.html" class="btn btn-danger"><i class="fa fa-trash-o"></i> Excluir</a>
              </div>
            </td>
          </tr>

        </table>
      </div>
      <!-- /.box-body -->

    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
